version: "3.7"

services:
  
  file-assets:
    build:
      context: .
    image: file-assets
    hostname: file-assets
    container_name: file-assets
    init: true
    restart: always
    environment:
      - HOST_GID=${HOST_GID:-1002}
      - HOST_UID=${HOST_UID:-1002}
    ports:
      - "8080:8080"
      - "8081:8081"
#      - "443:4430"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sennet_docker_network
    volumes:
      - "./log:/usr/src/app/log"
      - "./src/instance:/usr/src/app/src/instance"
      - "./src:/usr/src/app/src"
networks:
  # This is the network created by gateway to enable communication between multiple docker-compose projects
  sennet_docker_network:
    external: true
