version: "3.7"

services:
  file-assets:
    volumes:
      # Mount conf.d on host machine to the nginx conf.d on container
      - "./nginx/prod/conf.d:/etc/nginx/conf.d"
      - "../../../codcc/data:/codcc/data"